python run_pretraining.py \
--bert_config_file=configs/bert-base-cased-config.json \
--input_file=gs://span-pretraining-europe/data/only_recurring_50_tfrecords/*.tfrecord \
--output_dir=gs://span-pretraining-europe/model_outputs/splinter_no_mlm_50_long \
--max_seq_length=512 \
--recurring_span_masking=True \
--only_recurring_span_masking=True \
--max_recurring_predictions_per_seq=50 \
--do_train \
--train_batch_size=256 \
--learning_rate=1e-4 \
--num_train_steps=2400000 \
--num_warmup_steps=10000 \
--save_checkpoints_steps=10000 \
--keep_checkpoint_max=240 \
--use_tpu \
--num_tpu_cores=8 \
--tpu_name=no-mlm-50-tf
